import asyncio
import sys
from logging.config import fileConfig
from pathlib import Path

from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from alembic import context

# Add the project root to sys.path
sys.path.append(str(Path(__file__).resolve().parents[1]))

from app.core.config import settings
from app.core.infrastructure.db.base import Base

# Import all models to ensure they are attached to Base.metadata
# Datastore
from app.modules.datastore.infrastructure import models as datastore_models  # noqa: F401

# Identity
from app.modules.identity.infrastructure import models as identity_models  # noqa: F401

# Pod
from app.modules.pod.infrastructure import models as pod_models  # noqa: F401

# Agent
from app.modules.agent.infrastructure import models as agent_models  # noqa: F401

# Trigger
from app.modules.schedule.infrastructure import models as trigger_models  # noqa: F401

# Connectors
from app.modules.connectors.infrastructure import models as connector_models  # noqa: F401
from app.modules.function.infrastructure import models as function_models  # noqa: F401
from app.modules.apps.infrastructure import models as app_models  # noqa: F401
from app.modules.workflow.infrastructure import models as workflow_models  # noqa: F401
from app.modules.agent_surfaces.infrastructure import models as surface_models  # noqa: F401

# Usage / metering (usage_records, usage_limit_counters)
from app.modules.usage.infrastructure import models as usage_models  # noqa: F401

# Pod import (stateful, resumable bundle imports)
from app.modules.pod_import.infrastructure import models as pod_import_models  # noqa: F401

config = context.config

# Interpret the config file for Python logging.
# This line sets up loggers basically.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Set the sqlalchemy.url from the application settings
config.set_main_option("sqlalchemy.url", settings.database_url.replace("%", "%%"))

target_metadata = Base.metadata


def render_item(type_, obj, autogen_context):
    """Apply custom rendering for selected items."""
    # check if the item is a type
    return False


def include_object(object, name, type_, reflected, compare_to):
    """
    Should you include this object in the autogenerated migration?
    """
    if type_ == "table" and name == "apscheduler_jobs":
        return False
    return True


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.

    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        render_item=render_item,
        include_object=include_object,
    )

    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        render_item=render_item,
        include_object=include_object,
    )

    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online() -> None:
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.

    """
    configuration = config.get_section(config.config_ini_section) or {}
    configuration["sqlalchemy.url"] = settings.database_url

    connectable = async_engine_from_config(
        configuration,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
